#define BUFFER_WIDTH 320
#define BUFFER_HEIGHT 240
#define DISPLAY_SCALE 3
#define DISPLAY_WIDTH (BUFFER_WIDTH * DISPLAY_SCALE)
#define DISPLAY_HEIGHT (BUFFER_HEIGHT * DISPLAY_SCALE)
#define KEY_SEEN 1
#define KEY_RELEASED 2

#define ROCKFORD_WIDTH 24
#define ROCKFORD_HEIGHT 30
#define ROCKFORD_SPEED 3
#define ROCKFORD_MAX_X (BUFFER_WIDTH - ROCKFORD_WIDTH)
#define ROCKFORD_MAX_Y (BUFFER_HEIGHT - ROCKFORD_HEIGHT)